### ISSUE TITLE
Forge 1.12 - 14.21.1.2395

### ISSUE THREAD

**Issue by nanabathman** [Jacky1356400/SimpleSponge#14]
> ---- Minecraft Crash Report ----
> // I feel sad now :(
> 
> Time: 7/4/17 11:29 AM
> Description: There was a severe problem during mod loading that has caused the game to fail
> 
> net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Simple Sponge (simplesponge)
> Caused by: java.lang.NoClassDefFoundError: net/minecraftforge/fml/common/registry/IForgeRegistryEntry
> 	at me.jacky1356400.simplesponge.proxy.CommonProxy.preInit(CommonProxy.java:23)
> 	at me.jacky1356400.simplesponge.proxy.ClientProxy.preInit(ClientProxy.java:12)
> 	at me.jacky1356400.simplesponge.SimpleSponge.preInit(SimpleSponge.java:27)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
> 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> 	at java.lang.reflect.Method.invoke(Method.java:483)
> 	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:628)
> 	at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source)
> 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> 	at java.lang.reflect.Method.invoke(Method.java:483)
> 	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
> 	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
> 	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
> 	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
> 	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
> 	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
> 	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
> 	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:252)
> 	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:230)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
> 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> 	at java.lang.reflect.Method.invoke(Method.java:483)
> 	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
> 	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
> 	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
> 	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
> 	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
> 	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
> 	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
> 	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:147)
> 	at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:604)
> 	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:266)
> 	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:466)
> 	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:377)
> 	at net.minecraft.client.main.Main.main(SourceFile:123)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
> 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> 	at java.lang.reflect.Method.invoke(Method.java:483)
> 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
> 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
> Caused by: java.lang.ClassNotFoundException: net.minecraftforge.fml.common.registry.IForgeRegistryEntry
> 	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
> 	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
> 	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
> 	... 43 more
> Caused by: java.lang.NullPointerException
> 	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182)
> 	... 45 more
> 
> 
> A detailed walkthrough of the error, its code path and all known details is as follows:
> ---------------------------------------------------------------------------------------
> 
> -- System Details --
> Details:
> 	Minecraft Version: 1.12
> 	Operating System: Windows 7 (amd64) version 6.1
> 	Java Version: 1.8.0_25, Oracle Corporation
> 	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
> 	Memory: 86697960 bytes (82 MB) / 322174976 bytes (307 MB) up to 1060372480 bytes (1011 MB)
> 	JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx1G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
> 	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
> 	FML: MCP 9.40 Powered by Forge 14.21.1.2395 14 mods loaded, 14 mods active
> 	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
> 	UCH	minecraft{1.12} [Minecraft] (minecraft.jar) 
> 	UCH	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
> 	UCH	FML{8.0.99.99} [Forge Mod Loader] (forge-1.12-14.21.1.2395.jar) 
> 	UCH	forge{14.21.1.2395} [Minecraft Forge] (forge-1.12-14.21.1.2395.jar) 
> 	UCH	cropexp{1.0} [Crops Experience] (cropExp-1.0.jar) 
> 	UCH	easybreeding{5.0.0} [EasyBreeding] (easybreading-1.12-5.0.0.jar) 
> 	UCH	forgivingvoid{1.0.1} [Forgiving Void] (ForgivingVoid_1.12-1.0.1.jar) 
> 	UCH	llor{1.1.4-mc1.12} [Light Level Overlay Reloaded] (LLOverlayReloaded-1.1.4-mc1.12.jar) 
> 	UCH	mclvlup{1.2} [MC lvl up] (mclvlup-1.6.1.jar) 
> 	UCH	oreexcavation{1.4.96} [OreExcavation] (OreExcavation-1.4.96 (1).jar) 
> 	UCE	simplesponge{3.1.1} [Simple Sponge] (SimpleSponge-1.12-3.1.1.jar) 
> 	UCH	stringyshears{1.0} [Stringy Shears] (stringyshears-1.0.jar) 
> 	UCH	trapcraft{v2.4.3a} [Trapcraft] (Trapcraft-1.12-v2.4.3a-universal.jar) 
> 	UCH	xaerominimap{1.13} [Xaero's Minimap] (Xaeros_Minimap_1.13_Forge_1.12.jar) 
> 	Loaded coremods (and transformers): 
> 	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.5.0 NVIDIA 373.06' Renderer: 'GeForce GTX 650 Ti/PCIe/SSE2'

**Comment by JackyyTV** [comment]
You're using version 3.1.1 of the mod, it's way outdated. Please update to version 3.3 as I've already fixed the mod with newer versions of Forge.
[Download link to version 3.3](https://minecraft.curseforge.com/projects/simple-sponge/files/2441313)
