### ISSUE TITLE
Invalid Shaped Ore Recipe

### ISSUE THREAD

**Issue by Cazadorsniper** [Jacky1356400/SimpleSponge#15]
Crash during pack load.
crash-report: https://pastebin.com/p75e8HyP

**Comment by JackyyTV** [comment]
You probably have the OpenBlocks Sponges disabled and didn't disable OpenBlocks integration in Simple Sponge's config as well, so it's returning a null item on the recipe. I'll push a fix for that later today.

**Comment by JackyyTV** [comment]
@Cazadorsniper here's a new version with the fix, let me know if it works or not, so I can push that version to CurseForge.
[Download link](https://cdn.discordapp.com/attachments/363627996084568064/410373902192082944/SimpleSponge-1.12.2-3.6.1.jar)

**Comment by Cazadorsniper** [comment]
Yeah it works fine, also turned off the config as well.

**Comment by JackyyTV** [comment]
Alright that's good, I shall push the update to CurseForge now.
