### ISSUE TITLE
All sponges picking up all fluids

### ISSUE THREAD

**Issue by benbenlaw** [Jacky1356400/SimpleSponge#19]
sponge on a stick picks up lava?. should just the magmatic one do that

**Comment by JackyyTV** [comment]
This is intentional. Regular sponges / sponge on a stick are meant to only absorb lava once, then breaks. The magmatic variant just allows the sponges to be reused on lava.

**Comment by benbenlaw** [comment]
would it be possible to have a config for that setting? as its absorbs ALL other fluids

**Comment by JackyyTV** [comment]
Possibly, I'll have to look into adding a config option to not allow regular sponges absorb hot fluids like lava.

**Comment by benbenlaw** [comment]
thanks :)

**Comment by JackyyTV** [comment]
Config option added in [5.1](https://curseforge.com/minecraft/mc-mods/simple-sponge/files/4514391), allowing hot fluid is enabled by default and can be disabled via the new config option.
